### ISSUE TITLE
Path variable support

### ISSUE THREAD

**Issue by Vamic** [marcusolsson/grafana-json-datasource#18]
I saw this was mentioned in #8 and I'd also like to have the ability to set path variables.

I'm implementing a dashaboard for Pingdom and they use the format /api/2.1/summary.performance/{checkid} for requests, which requires a new data source for each checkid currently.

**Comment by marcusolsson** [comment]
It's been asked a few times, and I can see how it would be a useful feature. I'm not sure how this would work yet though.

1. **Add variable support to the URL:** This would give you a lot of freedom. You could create `https://api.example.com/${resource}`, or even `https://${environment}.example.com`. You wouldn't be able to test the data source, or to use it in Explore, or anywhere where variables aren't available.
1. **Set path in query editor:** This would add a field in the query editor that would be interpolated and added to the URL. Would this append to the path set in the data source config, or would it override it? Probably the latter.

I'd love more ideas on how you'd like this to work.

**Comment by Vamic** [comment]
I imagine you could use variables and then have the same UI as headers for setting the value of each of the variables, data source config could have all the default values, and then you can override them in the query editor.

**Comment by marcusolsson** [comment]
I think I'd like to use the built-in variables for this, rather than creating variables specifically for this data source (not sure if that's what you meant).

I'm leaning towards only making this configurable in the query editor to start with. A text field that would replace the path set by the data source.

- **URL** in data source config: `https://example.com/api
- **Path** in query editor: `/v2/api/${resource}`

Would result in `https://example.com/v2/api/orders` (when `resource` is `order`).

Another option would be to support _appending_ a path to the URL:

- **URL** in data source config: `https://example.com/v2/api
- **Path** in query editor: `/${resource}/list`

Would result in `https://example.com/v2/api/orders/list`

This sounds like it would solve your use case, while at the same time leaving options open for whether we want to be able to add this to the data source config?

**Comment by Vamic** [comment]
Sure, that will work. 
Appending makes the most sense to me but if you want the data source to have a default path replacing would be the way to go without needing config in the data source.

As an aside, this isn't in my use case or anything but if a variable is empty you might want to allow it to replace the // with /. Like if you have a variable for order_id and its empty it'll grab all orders by calling /api/orders/details instead of /api/orders//details.

**Comment by marcusolsson** [comment]
Appending would also make sense from the perspective of permissions.

You could set up data sources where the administrator wants to only allow access to resources under a certain path. For example, `https://example.com/api/tenants/abc123`. Allowing the users to replace the path completely would prevent this use case.

I think I have enough to start working on this. Thanks for helping me hash this out! 

Also, good point about replacing `//` with `/`. I'll make sure to add it 👍
