### ISSUE TITLE
Grafana global variables not working with JSONata

### ISSUE THREAD

**Issue by amng** [marcusolsson/grafana-json-datasource#222]
When trying to use one of the grafana default global variables (https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/) such as $__to or $__from there is no result for JSONata but for JSONPath it works as expected.
It also seems like the ${var} notation doesn't work for JSONata.

Working Example:
![image](https://user-images.githubusercontent.com/6146620/146045104-d7a8206f-b0b6-4ae9-b5be-ec6821ea4745.png)

Non Working Example:
![image](https://user-images.githubusercontent.com/6146620/146045011-376c094c-65fb-410f-b42f-ec3e35a9256b.png)

**Comment by marcusolsson** [comment]
Since variables are part of JSONata, I decided it would be a more idiomatic approach to use that instead of the Grafana intepolation. But I realize now that I forgot to add the global variables. 

Also, I didn't know JSONata well enough to know whether the Grafana syntax for variable interpolation would conflict with the syntax for JSONata.

**Comment by txjmb** [comment]
Any chance this can be added to a 1.3.1 version?
