### ISSUE TITLE
bad gateway error when running this plugin in a local instance of grafana and where to change base url?

### ISSUE THREAD

**Issue by casieo** [marcusolsson/grafana-json-datasource#33]
Hi,

I'm playing with this with the end goal of being able to query a couple sprinklr api's directly from grafana.  I have the plugin loaded, but when I use it as a datasource for a dashboard, I get this:
`Bad Gateway
Object
status:502
statusText:"Bad Gateway"
data:Object
error:"Bad Gateway"
response:""
message:"Bad Gateway"
config:Object
url:"api/datasources/proxy/1"
method:"GET"
retry:0
headers:Object
hideFromInspector:false
message:"Bad Gateway"`

Any tips on what to try to solve that?

Also, I've searched fairly extensively through the package files to determine where to change the base url, but am not finding it.  Can you help with that?

Thanks!

**Comment by marcusolsson** [comment]
Can you see any logs from the grafana-server? I'm not familiar with sprinklr unfortunately. Do they have a public/test API that I can reproduce this with? How are you authenticating against their APIs?

**Comment by casieo** [comment]
Thanks for the reply.  I checked the log, and here's what seems relevent:
"t=2021-01-09T21:26:31-0800 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1 remote_addr=[::1] referer="http://localhost:3000/dashboard/new?editPanel=2&orgId=1" error="http: proxy error: http: no Host in request URL"

Which I think (?) gets back to the question I asked about where to change the base url.   Sorry if I missed in the readme where to do that, I did search for it.  Unfortunately sprinklr isn't public.  I will need to authenticate against it.  That was going to be the next bridge

**Comment by marcusolsson** [comment]
I'm not sure what you mean by "base URL" here. You need to enter the URL to the API in the data source config. I can reproduce this if I remove the host in the data source config.

Could you confirm that you're using an absolute URL, such as `https://api.sprinklr.com/metrics`, rather than just `/metrics`? Could also be a typo in the URL preventing the plugin to detect the host part.

<img width="945" alt="Screen Shot 2021-01-10 at 11 37 31" src="https://user-images.githubusercontent.com/8396880/104120590-3ce75680-5338-11eb-828f-5f7030d6b9c5.png">

**Comment by marcusolsson** [comment]
I can imagine you'd get this if you left the data source config empty and only used the path in the query editor as well.

**Comment by casieo** [comment]
Thanks again!  I must have gotten mixed up somewhere but your explanation (and the screen shot) got me past this error.
