### ISSUE TITLE
ability to do arithmetic  on fields

### ISSUE THREAD

**Issue by wulfuric** [marcusolsson/grafana-json-datasource#96]
Hello, thanks for your great library, I did hit some initial issues in trying to set it up hitting an API that goes through a load balancer with a bearer token, ultimately I was able to hit the url directly and it worked but now I'm up and running!

Now that I've got it up and running, I have a table with a start time, and completion time, is there any way to do a subtraction of those two fields? I didn't come across it in the docs,, and poked around and tried some stuff. This is not a major blocker, I could definitely emit that to the JSON data as well from the API down the line, but figured I'd check and see if it's possible.

thanks again!

**Comment by marcusolsson** [comment]
Hey, and thanks for trying out the plugin! Unfortunately, the plugin doesn't support any transformation or processing of data. This has been a conscious design decision to focus on querying and filtering of data, and leave processing of data to Grafana itself through [Transformations](https://grafana.com/docs/grafana/latest/panels/transformations/#transformations) and potentially [server-side expressions](https://grafana.com/docs/grafana/latest/panels/expressions/#server-side-expressions) in the future. 

I'm not completely shutting down the idea of processing data in the plugin, but since data processing like the one you're mentioning would be better implemented in Grafana so that every data source would benefit.

**Comment by wulfuric** [comment]
Sounds good, looks like I'll have to try out those experimental features, thanks for the quick response!  Feel free to close this issue if you want.
